const express = require('express')
const adminRouter = express.Router()
const adminController = require('../Controller/admin.controller')
adminRouter.get('/', adminController.test)
adminRouter.post('/award', adminController.postAward)
adminRouter.get('/getaward', adminController.getAward)
adminRouter.post('/edit-award', adminController.editAward)
adminRouter.post('/delete-award', adminController.deleteAward)
adminRouter.get('/admissionReq', adminController.admissionReq)
adminRouter.post('/admission', adminController.admissionFunc)
adminRouter.post('/from-principal', adminController.principalNote)
adminRouter.get('/to-principal', adminController.getprincipal)
adminRouter.post('/gallery', adminController.galleryFunc)
adminRouter.get('/getGallery', adminController.getGallery)
adminRouter.post('/login', adminController.adminLogin)
adminRouter.get('/adminHome', adminController.adminHome)
module.exports = adminRouter